on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call: {}

name: Test

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN TAP and Wintun
        run: .\.github\InstallTUNTAP.ps1
        if: matrix.os == 'windows-latest'

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Build
        run: go build ./...

      - name: Test
        run: sudo go test ./...
        if: matrix.os != 'windows-latest'
      - name: Test
        run: go test ./...
        if: matrix.os == 'windows-latest'
