on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call: {}

name: Test

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Build
        run: go build ./...
      - name: Test
        run: sudo go test ./...

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenVPN TAP
        run: .\.github\InstallTAP.ps1
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...

  test-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Build
        run: go build ./...
      - name: Test
        run: sudo go test ./...
