on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call: {}

name: Test

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Windows tools
        run: |
          .\.github\InstallShims.ps1
          .\.github\InstallDrivers.ps1
        if: matrix.os == 'windows-latest'

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Build
        run: go build ./...

      - name: Test
        run: sudo go test ./...
